### ISSUE TITLE
Unable to send to 3dsmax

### ISSUE THREAD

**Issue by 4698to** [Sugz/VSCode-SendTo3dsMax#2]
2022-12-20 21:43:31.694 [error] TypeError: The "path" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at validateString (node:internal/validators:120:11)
	at Object.extname (node:path:837:5)
	at getCmdFromFile (c:\Users\joe\.vscode\extensions\clementplantec.send-to-3dsmax-0.1.5\src\extension.js:40:20)
	at c:\Users\joe\.vscode\extensions\clementplantec.send-to-3dsmax-0.1.5\src\extension.js:212:16
	at s.h (c:\Users\joe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:107622)
	at s.$executeContributedCommand (c:\Users\joe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:108311)

**Comment by NTKKS** [comment]
Got the same error, my 3ds Max is not installed in default C:/ location if that helps.

**Comment by eldeesmith** [comment]
same error. 

some quick debugging shows that a condition isn't handled for when your script is already saved (not dirty/not temp). I handled that condition, which takes care of the error- but 3dsmax doesn't seem to respond to the extension. I don't see anything show up in max's listener. No idea what's up, and at the moment I don't have a ton of time to debug it- but seems safe to assume that this extension isn't really ready for prime time.
